<?php

namespace App\Http\Controllers;

use App\Models\Criterion;
use App\Models\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class QuestionController extends Controller
{
    public function store(Request $request, Criterion $criterion)
    {
        abort_unless($criterion->tender->user_id === Auth::id(), 403);

        $validated = $request->validate([
            'question_text' => 'required|string',
            'priority' => 'nullable|in:normal,high,critical',
        ]);

        $validated['source'] = 'manual';
        $validated['sort_order'] = $criterion->questions()->max('sort_order') + 1;

        $criterion->questions()->create($validated);

        return back()->with('success', 'Question added.');
    }

    public function update(Request $request, Question $question)
    {
        abort_unless($question->criterion->tender->user_id === Auth::id(), 403);

        $validated = $request->validate([
            'question_text' => 'required|string',
            'priority' => 'nullable|in:normal,high,critical',
        ]);

        $question->update($validated);

        return back()->with('success', 'Question updated.');
    }

    public function destroy(Question $question)
    {
        abort_unless($question->criterion->tender->user_id === Auth::id(), 403);
        $question->delete();
        return back()->with('success', 'Question removed.');
    }

    public function generate(Criterion $criterion)
    {
        abort_unless($criterion->tender->user_id === Auth::id(), 403);

        // Simulated AI question generation for demo
        $tender = $criterion->tender;
        $templates = $this->getTemplateQuestions($criterion->name, $tender->description ?? '', $tender->objectives ?? '');

        $sortOrder = $criterion->questions()->max('sort_order') ?? 0;
        foreach ($templates as $q) {
            $criterion->questions()->create([
                'question_text' => $q['text'],
                'priority' => $q['priority'],
                'source' => 'ai_generated',
                'sort_order' => ++$sortOrder,
            ]);
        }

        return back()->with('success', count($templates) . ' questions generated by AI.');
    }

    private function getTemplateQuestions(string $criterionName, string $description, string $objectives): array
    {
        $name = strtolower($criterionName);

        if (str_contains($name, 'technical') || str_contains($name, 'technology')) {
            return [
                ['text' => 'What specific technologies and frameworks do you propose for this solution, and why are they the best fit?', 'priority' => 'high'],
                ['text' => 'How will your proposed architecture handle scalability requirements as usage grows?', 'priority' => 'normal'],
                ['text' => 'What is your approach to ensuring data security and GDPR compliance throughout the system?', 'priority' => 'critical'],
                ['text' => 'Describe your testing strategy, including unit tests, integration tests, and user acceptance testing.', 'priority' => 'normal'],
                ['text' => 'What monitoring and maintenance procedures will be in place post-deployment?', 'priority' => 'normal'],
            ];
        }

        if (str_contains($name, 'team') || str_contains($name, 'organization') || str_contains($name, 'personnel')) {
            return [
                ['text' => 'Describe the core team members and their relevant experience for this project.', 'priority' => 'high'],
                ['text' => 'How will knowledge transfer be handled to ensure continuity?', 'priority' => 'normal'],
                ['text' => 'What is your escalation process when key team members are unavailable?', 'priority' => 'normal'],
                ['text' => 'Provide examples of similar projects your team has successfully delivered.', 'priority' => 'high'],
            ];
        }

        if (str_contains($name, 'quality') || str_contains($name, 'assurance')) {
            return [
                ['text' => 'What quality assurance processes and standards will be applied throughout the project lifecycle?', 'priority' => 'high'],
                ['text' => 'How will you measure and report on quality metrics?', 'priority' => 'normal'],
                ['text' => 'Describe your approach to continuous improvement based on feedback and lessons learned.', 'priority' => 'normal'],
                ['text' => 'What specific certifications or compliance standards does your organization maintain?', 'priority' => 'critical'],
            ];
        }

        if (str_contains($name, 'risk') || str_contains($name, 'mitigation')) {
            return [
                ['text' => 'Identify the top 5 risks you foresee for this project and your proposed mitigation strategies.', 'priority' => 'critical'],
                ['text' => 'How will you handle scope changes or requirement modifications during the project?', 'priority' => 'high'],
                ['text' => 'What contingency plans are in place for critical path delays?', 'priority' => 'high'],
                ['text' => 'Describe a past project where a significant risk materialized and how you managed it.', 'priority' => 'normal'],
            ];
        }

        if (str_contains($name, 'timeline') || str_contains($name, 'planning') || str_contains($name, 'schedule')) {
            return [
                ['text' => 'Provide a detailed project timeline with key milestones and deliverables.', 'priority' => 'high'],
                ['text' => 'What are the critical dependencies that could impact the schedule?', 'priority' => 'high'],
                ['text' => 'How will you communicate progress and handle timeline adjustments?', 'priority' => 'normal'],
                ['text' => 'What is your approach to parallel workstreams to optimize delivery speed?', 'priority' => 'normal'],
            ];
        }

        // Default questions for any criterion
        return [
            ['text' => "Describe your approach to addressing the '{$criterionName}' requirements outlined in the tender documentation.", 'priority' => 'high'],
            ['text' => "What specific methodologies or frameworks will you apply to ensure excellence in '{$criterionName}'?", 'priority' => 'normal'],
            ['text' => "Provide concrete examples from past projects that demonstrate your capability in '{$criterionName}'.", 'priority' => 'normal'],
            ['text' => "What measurable outcomes or KPIs do you propose for evaluating success in this area?", 'priority' => 'normal'],
            ['text' => "What potential challenges do you anticipate for '{$criterionName}', and how would you address them?", 'priority' => 'high'],
        ];
    }
}
